from typing import Literal, cast

GetProjectListModuleType = Literal[
    "AARP",
    "AASP",
    "AAST",
    "AI_AGENT_MLOPS",
    "AI_TEST_AUTOMATION",
    "AISRE",
    "CD",
    "CE",
    "CET",
    "CF",
    "CHAOS",
    "CI",
    "CODE",
    "CORE",
    "CV",
    "DBOPS",
    "DevopsEssentials",
    "FME",
    "GOVERNANCE",
    "HAR",
    "IACM",
    "IDP",
    "PLATFORM",
    "PMS",
    "RMG",
    "SEI",
    "SRM",
    "SSCA",
    "STO",
    "TEMPLATESERVICE",
]

GET_PROJECT_LIST_MODULE_TYPE_VALUES: set[GetProjectListModuleType] = {
    "AARP",
    "AASP",
    "AAST",
    "AI_AGENT_MLOPS",
    "AI_TEST_AUTOMATION",
    "AISRE",
    "CD",
    "CE",
    "CET",
    "CF",
    "CHAOS",
    "CI",
    "CODE",
    "CORE",
    "CV",
    "DBOPS",
    "DevopsEssentials",
    "FME",
    "GOVERNANCE",
    "HAR",
    "IACM",
    "IDP",
    "PLATFORM",
    "PMS",
    "RMG",
    "SEI",
    "SRM",
    "SSCA",
    "STO",
    "TEMPLATESERVICE",
}


def check_get_project_list_module_type(value: str) -> GetProjectListModuleType:
    if value in GET_PROJECT_LIST_MODULE_TYPE_VALUES:
        return cast(GetProjectListModuleType, value)
    raise TypeError(f"Unexpected value {value!r}. Expected one of {GET_PROJECT_LIST_MODULE_TYPE_VALUES!r}")
