from typing import Literal, cast

ManifestConfigType = Literal[
    "AsgAdditionalConfiguration",
    "AsgConfiguration",
    "AsgLaunchTemplate",
    "AsgScalingPolicy",
    "AsgScheduledUpdateGroupAction",
    "AwsLambdaFunctionAliasDefinition",
    "AwsLambdaFunctionDefinition",
    "AwsSamDirectory",
    "AzureContainerAppsConfiguration",
    "DeploymentRepo",
    "EcsScalableTargetDefinition",
    "EcsScalingPolicyDefinition",
    "EcsScheduledActionDefinition",
    "EcsServiceDefinition",
    "EcsTaskDefinition",
    "GoogleCloudFunctionDefinition",
    "GoogleCloudFunctionGenOneDefinition",
    "GoogleCloudRunJob",
    "GoogleCloudRunService",
    "GoogleMigAutoscalerConfiguration",
    "GoogleMigConfiguration",
    "GoogleMigHealthCheckConfiguration",
    "GoogleMigInstanceTemplate",
    "HelmChart",
    "HelmRepoOverride",
    "K8sManifest",
    "Kustomize",
    "KustomizePatches",
    "OpenshiftParam",
    "OpenshiftTemplate",
    "ReleaseRepo",
    "ServerlessAwsLambda",
    "TasAutoScaler",
    "TasManifest",
    "TasVars",
    "Values",
]

MANIFEST_CONFIG_TYPE_VALUES: set[ManifestConfigType] = {
    "AsgAdditionalConfiguration",
    "AsgConfiguration",
    "AsgLaunchTemplate",
    "AsgScalingPolicy",
    "AsgScheduledUpdateGroupAction",
    "AwsLambdaFunctionAliasDefinition",
    "AwsLambdaFunctionDefinition",
    "AwsSamDirectory",
    "AzureContainerAppsConfiguration",
    "DeploymentRepo",
    "EcsScalableTargetDefinition",
    "EcsScalingPolicyDefinition",
    "EcsScheduledActionDefinition",
    "EcsServiceDefinition",
    "EcsTaskDefinition",
    "GoogleCloudFunctionDefinition",
    "GoogleCloudFunctionGenOneDefinition",
    "GoogleCloudRunJob",
    "GoogleCloudRunService",
    "GoogleMigAutoscalerConfiguration",
    "GoogleMigConfiguration",
    "GoogleMigHealthCheckConfiguration",
    "GoogleMigInstanceTemplate",
    "HelmChart",
    "HelmRepoOverride",
    "K8sManifest",
    "Kustomize",
    "KustomizePatches",
    "OpenshiftParam",
    "OpenshiftTemplate",
    "ReleaseRepo",
    "ServerlessAwsLambda",
    "TasAutoScaler",
    "TasManifest",
    "TasVars",
    "Values",
}


def check_manifest_config_type(value: str) -> ManifestConfigType:
    if value in MANIFEST_CONFIG_TYPE_VALUES:
        return cast(ManifestConfigType, value)
    raise TypeError(f"Unexpected value {value!r}. Expected one of {MANIFEST_CONFIG_TYPE_VALUES!r}")
