#!/usr/bin/env bash
# Package harness-cli as a self-contained, regenerable tarball.
#
# The archive does NOT ship the generated SDKs (vendor/, ~25 MB). Instead it
# ships the OpenAPI specs (specs/) + scripts/vendor.sh, and the recipient
# regenerates vendor/ locally. So the tarball contains: CLI source, specs/,
# scripts/, pyproject.toml, uv.lock, .python-version, and .env.example
# (credential template). Credentials are NEVER included.
#
# Usage:
#   ./package.sh                     # -> ../harness-cli.tar.gz
#   ./package.sh /tmp/out.tar.gz     # custom output path
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
pkg_name="$(basename "$script_dir")"          # harness-cli
parent_dir="$(dirname "$script_dir")"
out="${1:-$parent_dir/$pkg_name.tar.gz}"

# vendor/ is regenerated by the recipient (scripts/vendor.sh) FROM specs/, so
# the specs must be present — otherwise the tarball couldn't regenerate.
if [ ! -f "$script_dir/specs/harness-code-openapi.yaml" ]; then
  echo "ERROR: specs/ is missing the OpenAPI specs — cannot build a regenerable tarball." >&2
  exit 1
fi

echo "Packaging '$pkg_name' -> $out"

# -C parent_dir so the archive root is harness-cli/, not an absolute path.
tar -C "$parent_dir" -czf "$out" \
  --exclude='__pycache__' \
  --exclude='*.py[cod]' \
  --exclude='*.egg-info' \
  --exclude='.eggs' \
  --exclude='.pytest_cache' \
  --exclude='.ruff_cache' \
  --exclude='.venv' \
  --exclude='venv' \
  --exclude='env' \
  --exclude='build' \
  --exclude='dist' \
  --exclude='.coverage' \
  --exclude='htmlcov' \
  --exclude='.DS_Store' \
  --exclude='.env' \
  --exclude='vendor' \
  "$pkg_name"

size="$(du -h "$out" | cut -f1)"
echo "Done ($size). vendor/ is excluded — recipient runs ./scripts/vendor.sh to build it."
echo ""
echo "Recipient setup:"
echo "  tar -xzf $out && cd $pkg_name"
echo "  ./scripts/vendor.sh                 # regenerate vendor/ from specs/"
echo "  cp .env.example .env && edit .env   # add your Harness credentials"
echo "  uv sync && uv run --env-file .env harness-cli --help"
