trigger:
  name: dev branch create
  identifier: dev_build_branch_create
  enabled: true
  orgIdentifier: ${org_id}
  projectIdentifier: ${project_id}
  pipelineIdentifier: dev_build
  source:
    type: Webhook
    spec:
      type: Harness
      spec:
        type: Branch
        spec:
          connectorRef: ""
          autoAbortPreviousExecutions: true
          payloadConditions:
            - key: targetBranch
              operator: StartsWith
              value: "dev/"
          headerConditions: []
          repoName: image-build
          actions:
            - Create
  inputYaml: |
    pipeline:
      identifier: dev_build
      properties:
        ci:
          codebase:
            build:
              type: branch
              spec:
                branch: <+trigger.branch>
