trigger:
  name: main push
  identifier: main_release_push
  enabled: true
  orgIdentifier: ${org_id}
  projectIdentifier: ${project_id}
  pipelineIdentifier: main_release
  source:
    type: Webhook
    spec:
      type: Harness
      spec:
        type: Push
        spec:
          connectorRef: ""
          autoAbortPreviousExecutions: false
          payloadConditions:
            - key: targetBranch
              operator: Equals
              value: "main"
          headerConditions: []
          repoName: image-build
          actions: []
  inputYaml: |
    pipeline:
      identifier: main_release
      properties:
        ci:
          codebase:
            build:
              type: branch
              spec:
                branch: <+trigger.branch>
