from typing import Literal, cast

ExecutionInfoStatus = Literal[
    "Aborted",
    "AbortedByFreeze",
    "APPROVAL_REJECTED",
    "APPROVAL_WAITING",
    "ApprovalRejected",
    "ApprovalWaiting",
    "AsyncWaiting",
    "Discontinuing",
    "Errored",
    "Expired",
    "Failed",
    "IgnoreFailed",
    "InputWaiting",
    "INTERVENTION_WAITING",
    "InterventionWaiting",
    "NOT_STARTED",
    "NotStarted",
    "Paused",
    "Pausing",
    "Queued",
    "QueuedExecutionConcurrencyReached",
    "QueuedGlobalInfraCapacityReached",
    "QueuedLicenseLimitReached",
    "ResourceWaiting",
    "Running",
    "Skipped",
    "Success",
    "Suspended",
    "TaskWaiting",
    "TimedWaiting",
    "UploadWaiting",
    "Waiting",
    "WaitStepRunning",
]

EXECUTION_INFO_STATUS_VALUES: set[ExecutionInfoStatus] = {
    "Aborted",
    "AbortedByFreeze",
    "APPROVAL_REJECTED",
    "APPROVAL_WAITING",
    "ApprovalRejected",
    "ApprovalWaiting",
    "AsyncWaiting",
    "Discontinuing",
    "Errored",
    "Expired",
    "Failed",
    "IgnoreFailed",
    "InputWaiting",
    "INTERVENTION_WAITING",
    "InterventionWaiting",
    "NOT_STARTED",
    "NotStarted",
    "Paused",
    "Pausing",
    "Queued",
    "QueuedExecutionConcurrencyReached",
    "QueuedGlobalInfraCapacityReached",
    "QueuedLicenseLimitReached",
    "ResourceWaiting",
    "Running",
    "Skipped",
    "Success",
    "Suspended",
    "TaskWaiting",
    "TimedWaiting",
    "UploadWaiting",
    "Waiting",
    "WaitStepRunning",
}


def check_execution_info_status(value: str) -> ExecutionInfoStatus:
    if value in EXECUTION_INFO_STATUS_VALUES:
        return cast(ExecutionInfoStatus, value)
    raise TypeError(f"Unexpected value {value!r}. Expected one of {EXECUTION_INFO_STATUS_VALUES!r}")
