from typing import Literal, cast

ExecutionSummaryInfoLastExecutionStatus = Literal[
    "Aborted",
    "AbortedByFreeze",
    "APPROVAL_REJECTED",
    "APPROVAL_WAITING",
    "ApprovalRejected",
    "ApprovalWaiting",
    "AsyncWaiting",
    "Discontinuing",
    "Errored",
    "Expired",
    "Failed",
    "IgnoreFailed",
    "InputWaiting",
    "INTERVENTION_WAITING",
    "InterventionWaiting",
    "NOT_STARTED",
    "NotStarted",
    "Paused",
    "Pausing",
    "Queued",
    "QueuedExecutionConcurrencyReached",
    "QueuedGlobalInfraCapacityReached",
    "QueuedLicenseLimitReached",
    "ResourceWaiting",
    "Running",
    "Skipped",
    "Success",
    "Suspended",
    "TaskWaiting",
    "TimedWaiting",
    "UploadWaiting",
    "Waiting",
    "WaitStepRunning",
]

EXECUTION_SUMMARY_INFO_LAST_EXECUTION_STATUS_VALUES: set[ExecutionSummaryInfoLastExecutionStatus] = {
    "Aborted",
    "AbortedByFreeze",
    "APPROVAL_REJECTED",
    "APPROVAL_WAITING",
    "ApprovalRejected",
    "ApprovalWaiting",
    "AsyncWaiting",
    "Discontinuing",
    "Errored",
    "Expired",
    "Failed",
    "IgnoreFailed",
    "InputWaiting",
    "INTERVENTION_WAITING",
    "InterventionWaiting",
    "NOT_STARTED",
    "NotStarted",
    "Paused",
    "Pausing",
    "Queued",
    "QueuedExecutionConcurrencyReached",
    "QueuedGlobalInfraCapacityReached",
    "QueuedLicenseLimitReached",
    "ResourceWaiting",
    "Running",
    "Skipped",
    "Success",
    "Suspended",
    "TaskWaiting",
    "TimedWaiting",
    "UploadWaiting",
    "Waiting",
    "WaitStepRunning",
}


def check_execution_summary_info_last_execution_status(value: str) -> ExecutionSummaryInfoLastExecutionStatus:
    if value in EXECUTION_SUMMARY_INFO_LAST_EXECUTION_STATUS_VALUES:
        return cast(ExecutionSummaryInfoLastExecutionStatus, value)
    raise TypeError(
        f"Unexpected value {value!r}. Expected one of {EXECUTION_SUMMARY_INFO_LAST_EXECUTION_STATUS_VALUES!r}"
    )
