from typing import Literal, cast

FailureDataOrBuilderFailureTypesListItem = Literal[
    "APPLICATION_FAILURE",
    "APPROVAL_REJECTION",
    "AUTHENTICATION_FAILURE",
    "AUTHORIZATION_FAILURE",
    "CONFIGURATION_FAILURE",
    "CONNECTIVITY_FAILURE",
    "DELEGATE_PROVISIONING_FAILURE",
    "DELEGATE_RESTART",
    "FREEZE_ACTIVE_FAILURE",
    "INFRASTRUCTURE_FAILURE",
    "INPUT_TIMEOUT_FAILURE",
    "PLUGIN_IMAGE_FAILURE",
    "POLICY_EVALUATION_FAILURE",
    "RESOURCE_LIMITS_FAILURE",
    "RETRYABLE_TRANSIENT_FAILURE",
    "SKIPPING_FAILURE",
    "TIMEOUT_FAILURE",
    "UNKNOWN_FAILURE",
    "UNRECOGNIZED",
    "USER_MARKED_FAILURE",
    "VERIFICATION_FAILURE",
]

FAILURE_DATA_OR_BUILDER_FAILURE_TYPES_LIST_ITEM_VALUES: set[FailureDataOrBuilderFailureTypesListItem] = {
    "APPLICATION_FAILURE",
    "APPROVAL_REJECTION",
    "AUTHENTICATION_FAILURE",
    "AUTHORIZATION_FAILURE",
    "CONFIGURATION_FAILURE",
    "CONNECTIVITY_FAILURE",
    "DELEGATE_PROVISIONING_FAILURE",
    "DELEGATE_RESTART",
    "FREEZE_ACTIVE_FAILURE",
    "INFRASTRUCTURE_FAILURE",
    "INPUT_TIMEOUT_FAILURE",
    "PLUGIN_IMAGE_FAILURE",
    "POLICY_EVALUATION_FAILURE",
    "RESOURCE_LIMITS_FAILURE",
    "RETRYABLE_TRANSIENT_FAILURE",
    "SKIPPING_FAILURE",
    "TIMEOUT_FAILURE",
    "UNKNOWN_FAILURE",
    "UNRECOGNIZED",
    "USER_MARKED_FAILURE",
    "VERIFICATION_FAILURE",
}


def check_failure_data_or_builder_failure_types_list_item(value: str) -> FailureDataOrBuilderFailureTypesListItem:
    if value in FAILURE_DATA_OR_BUILDER_FAILURE_TYPES_LIST_ITEM_VALUES:
        return cast(FailureDataOrBuilderFailureTypesListItem, value)
    raise TypeError(
        f"Unexpected value {value!r}. Expected one of {FAILURE_DATA_OR_BUILDER_FAILURE_TYPES_LIST_ITEM_VALUES!r}"
    )
