from typing import Literal, cast

FailureInfoDTOFailureTypeListItem = Literal[
    "APPLICATION_ERROR",
    "APPROVAL_REJECTION",
    "AUTHENTICATION",
    "AUTHORIZATION_ERROR",
    "CONFIGURATION_FAILURE",
    "CONNECTIVITY",
    "DELEGATE_PROVISIONING",
    "DELEGATE_RESTART",
    "EXPIRED",
    "INFRASTRUCTURE_FAILURE",
    "INPUT_TIMEOUT_FAILURE",
    "PLUGIN_IMAGE_FAILURE",
    "POLICY_EVALUATION_FAILURE",
    "RESOURCE_LIMITS_FAILURE",
    "RETRYABLE_TRANSIENT_FAILURE",
    "TIMEOUT_ERROR",
    "USER_MARKED_FAILURE",
    "VERIFICATION_FAILURE",
]

FAILURE_INFO_DTO_FAILURE_TYPE_LIST_ITEM_VALUES: set[FailureInfoDTOFailureTypeListItem] = {
    "APPLICATION_ERROR",
    "APPROVAL_REJECTION",
    "AUTHENTICATION",
    "AUTHORIZATION_ERROR",
    "CONFIGURATION_FAILURE",
    "CONNECTIVITY",
    "DELEGATE_PROVISIONING",
    "DELEGATE_RESTART",
    "EXPIRED",
    "INFRASTRUCTURE_FAILURE",
    "INPUT_TIMEOUT_FAILURE",
    "PLUGIN_IMAGE_FAILURE",
    "POLICY_EVALUATION_FAILURE",
    "RESOURCE_LIMITS_FAILURE",
    "RETRYABLE_TRANSIENT_FAILURE",
    "TIMEOUT_ERROR",
    "USER_MARKED_FAILURE",
    "VERIFICATION_FAILURE",
}


def check_failure_info_dto_failure_type_list_item(value: str) -> FailureInfoDTOFailureTypeListItem:
    if value in FAILURE_INFO_DTO_FAILURE_TYPE_LIST_ITEM_VALUES:
        return cast(FailureInfoDTOFailureTypeListItem, value)
    raise TypeError(f"Unexpected value {value!r}. Expected one of {FAILURE_INFO_DTO_FAILURE_TYPE_LIST_ITEM_VALUES!r}")
