from typing import Literal, cast

FailureInfoFailureTypesListItem = Literal[
    "APPLICATION_FAILURE",
    "APPROVAL_REJECTION",
    "AUTHENTICATION_FAILURE",
    "AUTHORIZATION_FAILURE",
    "CONFIGURATION_FAILURE",
    "CONNECTIVITY_FAILURE",
    "DELEGATE_PROVISIONING_FAILURE",
    "DELEGATE_RESTART",
    "FREEZE_ACTIVE_FAILURE",
    "INFRASTRUCTURE_FAILURE",
    "INPUT_TIMEOUT_FAILURE",
    "PLUGIN_IMAGE_FAILURE",
    "POLICY_EVALUATION_FAILURE",
    "RESOURCE_LIMITS_FAILURE",
    "RETRYABLE_TRANSIENT_FAILURE",
    "SKIPPING_FAILURE",
    "TIMEOUT_FAILURE",
    "UNKNOWN_FAILURE",
    "UNRECOGNIZED",
    "USER_MARKED_FAILURE",
    "VERIFICATION_FAILURE",
]

FAILURE_INFO_FAILURE_TYPES_LIST_ITEM_VALUES: set[FailureInfoFailureTypesListItem] = {
    "APPLICATION_FAILURE",
    "APPROVAL_REJECTION",
    "AUTHENTICATION_FAILURE",
    "AUTHORIZATION_FAILURE",
    "CONFIGURATION_FAILURE",
    "CONNECTIVITY_FAILURE",
    "DELEGATE_PROVISIONING_FAILURE",
    "DELEGATE_RESTART",
    "FREEZE_ACTIVE_FAILURE",
    "INFRASTRUCTURE_FAILURE",
    "INPUT_TIMEOUT_FAILURE",
    "PLUGIN_IMAGE_FAILURE",
    "POLICY_EVALUATION_FAILURE",
    "RESOURCE_LIMITS_FAILURE",
    "RETRYABLE_TRANSIENT_FAILURE",
    "SKIPPING_FAILURE",
    "TIMEOUT_FAILURE",
    "UNKNOWN_FAILURE",
    "UNRECOGNIZED",
    "USER_MARKED_FAILURE",
    "VERIFICATION_FAILURE",
}


def check_failure_info_failure_types_list_item(value: str) -> FailureInfoFailureTypesListItem:
    if value in FAILURE_INFO_FAILURE_TYPES_LIST_ITEM_VALUES:
        return cast(FailureInfoFailureTypesListItem, value)
    raise TypeError(f"Unexpected value {value!r}. Expected one of {FAILURE_INFO_FAILURE_TYPES_LIST_ITEM_VALUES!r}")
