from typing import Literal, cast

FailureTypeInfoOrBuilderFailureType = Literal[
    "APPLICATION_FAILURE",
    "APPROVAL_REJECTION",
    "AUTHENTICATION_FAILURE",
    "AUTHORIZATION_FAILURE",
    "CONFIGURATION_FAILURE",
    "CONNECTIVITY_FAILURE",
    "DELEGATE_PROVISIONING_FAILURE",
    "DELEGATE_RESTART",
    "FREEZE_ACTIVE_FAILURE",
    "INFRASTRUCTURE_FAILURE",
    "INPUT_TIMEOUT_FAILURE",
    "PLUGIN_IMAGE_FAILURE",
    "POLICY_EVALUATION_FAILURE",
    "RESOURCE_LIMITS_FAILURE",
    "RETRYABLE_TRANSIENT_FAILURE",
    "SKIPPING_FAILURE",
    "TIMEOUT_FAILURE",
    "UNKNOWN_FAILURE",
    "UNRECOGNIZED",
    "USER_MARKED_FAILURE",
    "VERIFICATION_FAILURE",
]

FAILURE_TYPE_INFO_OR_BUILDER_FAILURE_TYPE_VALUES: set[FailureTypeInfoOrBuilderFailureType] = {
    "APPLICATION_FAILURE",
    "APPROVAL_REJECTION",
    "AUTHENTICATION_FAILURE",
    "AUTHORIZATION_FAILURE",
    "CONFIGURATION_FAILURE",
    "CONNECTIVITY_FAILURE",
    "DELEGATE_PROVISIONING_FAILURE",
    "DELEGATE_RESTART",
    "FREEZE_ACTIVE_FAILURE",
    "INFRASTRUCTURE_FAILURE",
    "INPUT_TIMEOUT_FAILURE",
    "PLUGIN_IMAGE_FAILURE",
    "POLICY_EVALUATION_FAILURE",
    "RESOURCE_LIMITS_FAILURE",
    "RETRYABLE_TRANSIENT_FAILURE",
    "SKIPPING_FAILURE",
    "TIMEOUT_FAILURE",
    "UNKNOWN_FAILURE",
    "UNRECOGNIZED",
    "USER_MARKED_FAILURE",
    "VERIFICATION_FAILURE",
}


def check_failure_type_info_or_builder_failure_type(value: str) -> FailureTypeInfoOrBuilderFailureType:
    if value in FAILURE_TYPE_INFO_OR_BUILDER_FAILURE_TYPE_VALUES:
        return cast(FailureTypeInfoOrBuilderFailureType, value)
    raise TypeError(f"Unexpected value {value!r}. Expected one of {FAILURE_TYPE_INFO_OR_BUILDER_FAILURE_TYPE_VALUES!r}")
