from typing import Literal, cast

GetListOfExecutionsStatusItem = Literal[
    "Aborted",
    "AbortedByFreeze",
    "APPROVAL_REJECTED",
    "APPROVAL_WAITING",
    "ApprovalRejected",
    "ApprovalWaiting",
    "AsyncWaiting",
    "Discontinuing",
    "Errored",
    "Expired",
    "Failed",
    "IgnoreFailed",
    "InputWaiting",
    "INTERVENTION_WAITING",
    "InterventionWaiting",
    "NOT_STARTED",
    "NotStarted",
    "Paused",
    "Pausing",
    "Queued",
    "QueuedExecutionConcurrencyReached",
    "QueuedGlobalInfraCapacityReached",
    "QueuedLicenseLimitReached",
    "ResourceWaiting",
    "Running",
    "Skipped",
    "Success",
    "Suspended",
    "TaskWaiting",
    "TimedWaiting",
    "UploadWaiting",
    "Waiting",
    "WaitStepRunning",
]

GET_LIST_OF_EXECUTIONS_STATUS_ITEM_VALUES: set[GetListOfExecutionsStatusItem] = {
    "Aborted",
    "AbortedByFreeze",
    "APPROVAL_REJECTED",
    "APPROVAL_WAITING",
    "ApprovalRejected",
    "ApprovalWaiting",
    "AsyncWaiting",
    "Discontinuing",
    "Errored",
    "Expired",
    "Failed",
    "IgnoreFailed",
    "InputWaiting",
    "INTERVENTION_WAITING",
    "InterventionWaiting",
    "NOT_STARTED",
    "NotStarted",
    "Paused",
    "Pausing",
    "Queued",
    "QueuedExecutionConcurrencyReached",
    "QueuedGlobalInfraCapacityReached",
    "QueuedLicenseLimitReached",
    "ResourceWaiting",
    "Running",
    "Skipped",
    "Success",
    "Suspended",
    "TaskWaiting",
    "TimedWaiting",
    "UploadWaiting",
    "Waiting",
    "WaitStepRunning",
}


def check_get_list_of_executions_status_item(value: str) -> GetListOfExecutionsStatusItem:
    if value in GET_LIST_OF_EXECUTIONS_STATUS_ITEM_VALUES:
        return cast(GetListOfExecutionsStatusItem, value)
    raise TypeError(f"Unexpected value {value!r}. Expected one of {GET_LIST_OF_EXECUTIONS_STATUS_ITEM_VALUES!r}")
