from typing import Literal, cast

QueuedPipelineFilterStatusesItem = Literal[
    "Aborted",
    "AbortedByFreeze",
    "APPROVAL_REJECTED",
    "APPROVAL_WAITING",
    "ApprovalRejected",
    "ApprovalWaiting",
    "AsyncWaiting",
    "Discontinuing",
    "Errored",
    "Expired",
    "Failed",
    "IgnoreFailed",
    "InputWaiting",
    "INTERVENTION_WAITING",
    "InterventionWaiting",
    "NOT_STARTED",
    "NotStarted",
    "Paused",
    "Pausing",
    "Queued",
    "QueuedExecutionConcurrencyReached",
    "QueuedGlobalInfraCapacityReached",
    "QueuedLicenseLimitReached",
    "ResourceWaiting",
    "Running",
    "Skipped",
    "Success",
    "Suspended",
    "TaskWaiting",
    "TimedWaiting",
    "UploadWaiting",
    "Waiting",
    "WaitStepRunning",
]

QUEUED_PIPELINE_FILTER_STATUSES_ITEM_VALUES: set[QueuedPipelineFilterStatusesItem] = {
    "Aborted",
    "AbortedByFreeze",
    "APPROVAL_REJECTED",
    "APPROVAL_WAITING",
    "ApprovalRejected",
    "ApprovalWaiting",
    "AsyncWaiting",
    "Discontinuing",
    "Errored",
    "Expired",
    "Failed",
    "IgnoreFailed",
    "InputWaiting",
    "INTERVENTION_WAITING",
    "InterventionWaiting",
    "NOT_STARTED",
    "NotStarted",
    "Paused",
    "Pausing",
    "Queued",
    "QueuedExecutionConcurrencyReached",
    "QueuedGlobalInfraCapacityReached",
    "QueuedLicenseLimitReached",
    "ResourceWaiting",
    "Running",
    "Skipped",
    "Success",
    "Suspended",
    "TaskWaiting",
    "TimedWaiting",
    "UploadWaiting",
    "Waiting",
    "WaitStepRunning",
}


def check_queued_pipeline_filter_statuses_item(value: str) -> QueuedPipelineFilterStatusesItem:
    if value in QUEUED_PIPELINE_FILTER_STATUSES_ITEM_VALUES:
        return cast(QueuedPipelineFilterStatusesItem, value)
    raise TypeError(f"Unexpected value {value!r}. Expected one of {QUEUED_PIPELINE_FILTER_STATUSES_ITEM_VALUES!r}")
