from typing import Literal, cast

ResponseMessageFailureTypesItem = Literal[
    "APPLICATION_ERROR",
    "APPROVAL_REJECTION",
    "AUTHENTICATION",
    "AUTHORIZATION_ERROR",
    "CONFIGURATION_FAILURE",
    "CONNECTIVITY",
    "DELEGATE_PROVISIONING",
    "DELEGATE_RESTART",
    "EXPIRED",
    "INFRASTRUCTURE_FAILURE",
    "INPUT_TIMEOUT_FAILURE",
    "PLUGIN_IMAGE_FAILURE",
    "POLICY_EVALUATION_FAILURE",
    "RESOURCE_LIMITS_FAILURE",
    "RETRYABLE_TRANSIENT_FAILURE",
    "TIMEOUT_ERROR",
    "USER_MARKED_FAILURE",
    "VERIFICATION_FAILURE",
]

RESPONSE_MESSAGE_FAILURE_TYPES_ITEM_VALUES: set[ResponseMessageFailureTypesItem] = {
    "APPLICATION_ERROR",
    "APPROVAL_REJECTION",
    "AUTHENTICATION",
    "AUTHORIZATION_ERROR",
    "CONFIGURATION_FAILURE",
    "CONNECTIVITY",
    "DELEGATE_PROVISIONING",
    "DELEGATE_RESTART",
    "EXPIRED",
    "INFRASTRUCTURE_FAILURE",
    "INPUT_TIMEOUT_FAILURE",
    "PLUGIN_IMAGE_FAILURE",
    "POLICY_EVALUATION_FAILURE",
    "RESOURCE_LIMITS_FAILURE",
    "RETRYABLE_TRANSIENT_FAILURE",
    "TIMEOUT_ERROR",
    "USER_MARKED_FAILURE",
    "VERIFICATION_FAILURE",
}


def check_response_message_failure_types_item(value: str) -> ResponseMessageFailureTypesItem:
    if value in RESPONSE_MESSAGE_FAILURE_TYPES_ITEM_VALUES:
        return cast(ResponseMessageFailureTypesItem, value)
    raise TypeError(f"Unexpected value {value!r}. Expected one of {RESPONSE_MESSAGE_FAILURE_TYPES_ITEM_VALUES!r}")
